import {UserLdap} from "./user-ldap";

export const LDAP_USERS: UserLdap[]=[
  {
    id : 1,
    login: 'test.v1',
    nom:'V1',
    prenom:'Test',
    nomComplet:'V1 Test',
    motDePasse: "null",
    mail:'test.v1@eps.fr',
    role  :'ROLE_USER',
    employeNumero:1234,
    employeNiveau:120,
    dateEmbauche:'2020-01-01',
    publisherId:1,
    active:true,
  },
  {
    id:2,
    login: 'test.v2',
    nom:'V2',
    prenom:'Test',
    nomComplet:'V2 Test',
    motDePasse:"null",
    mail:'test.v2@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2234,
    employeNiveau:220,
    dateEmbauche:'2020-02-02',
    publisherId:2,
    active:true,
  },
  {
    id:3,
    login: 'test.v3',
    nom:'V3',
    prenom:'Test',
    nomComplet:'V3 Test',
    motDePasse:"null",
    mail:'test.v3@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2235,
    employeNiveau:221,
    dateEmbauche:'2020-02-02',
    publisherId:3,
    active:true,
  },
  {
    id:4,
    login: 'test.v4',
    nom:'V4',
    prenom:'Test',
    nomComplet:'V4 Test',
    motDePasse:"null",
    mail:'test.v4@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2236,
    employeNiveau:222,
    dateEmbauche:'2020-02-02',
    publisherId:4,
    active:true,
  },
  {
    id:5,
    login: 'test.v5',
    nom:'V5',
    prenom:'Test',
    nomComplet:'V5 Test',
    motDePasse:"null",
    mail:'test.v5@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2237,
    employeNiveau:223,
    dateEmbauche:'2020-02-02',
    publisherId:5,
    active:true,
  },
  {
    id:6,
    login: 'test.v6',
    nom:'V6',
    prenom:'Test',
    nomComplet:'V6 Test',
    motDePasse:"null",
    mail:'test.v6@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2238,
    employeNiveau:224,
    dateEmbauche:'2020-02-02',
    publisherId:6,
    active:true,
  },
  {
    id:7,
    login: 'test.v7',
    nom:'V7',
    prenom:'Test',
    nomComplet:'V7 Test',
    motDePasse:"null",
    mail:'test.v7@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2239,
    employeNiveau:225,
    dateEmbauche:'2020-02-02',
    publisherId:7,
    active:true,
  },
  {
    id:8,
    login: 'test.v8',
    nom:'V8',
    prenom:'Test',
    nomComplet:'V8 Test',
    motDePasse:"null",
    mail:'test.v8@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2240,
    employeNiveau:226,
    dateEmbauche:'2020-02-02',
    publisherId:8,
    active:true,
  },
  {
    id:9,
    login: 'test.v9',
    nom:'V9',
    prenom:'Test',
    nomComplet:'V9 Test',
    motDePasse:"null",
    mail:'test.v9@eps.fr',
    role  :'ROLE_USER',
    employeNumero:2241,
    employeNiveau:227,
    dateEmbauche:'2020-02-02',
    publisherId:9,
    active:true,
  },



];
